name: Build and Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Nodejs app
        uses: applebot/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir test
            cd test
            git clone git@github.com:Vicra/collection-tracker-api.git
            echo 'Deployment successful to digital ocean'
